name: shrine
description: Learn the basics of using Material Components by building a simple app with core components.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.2
  go_router: ^16.2.4

  cupertino_icons: ^1.0.5
  shrine_images: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/recomecha.png
    - assets/recomechalogo.png
    # TODO: Add slanted menu asset (104)
    - assets/slanted_menu.png
    - assets/0.png
    - assets/1.png
    - assets/2.png    
    - assets/3.png
    - assets/4.png
    - assets/5.png
    - assets/6.png
    - assets/7.png
    - assets/8.png
    - assets/9.png
    - assets/10.png
    - assets/11.png
    - assets/12.png
    - assets/13.png
    - assets/14.png
    - assets/15.png
    - assets/16.png
    - assets/17.png
    - assets/18.png
    - assets/19.png 
    - assets/20.png
    - assets/21.png
    - assets/22.png
    - assets/23.png
    - assets/24.png
    - assets/25.png
    - assets/26.png
    - assets/27.png
    - assets/28.png
    - assets/29.png
    - assets/30.png 
    - assets/31.png
    - assets/32.png
    - assets/33.png
    - assets/34.png
    - assets/35.png
    - assets/36.png
    - assets/37.png
    - assets/38.png

  # TODO: Insert Fonts (103)
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
